# Generated by Django 5.2.12 on 2026-03-24 00:36

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_attendancerecord_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogProxy',
            fields=[
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجل النشاطات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.activitylog',),
        ),
        migrations.CreateModel(
            name='DepartmentModelProxy',
            fields=[
            ],
            options={
                'verbose_name': 'قسم / إدارة',
                'verbose_name_plural': 'الأقسام والإدارات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.departmentmodel',),
        ),
        migrations.CreateModel(
            name='NotificationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.notification',),
        ),
        migrations.CreateModel(
            name='PayrollProxy',
            fields=[
            ],
            options={
                'verbose_name': 'كشف راتب',
                'verbose_name_plural': 'كشوف الرواتب',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.payroll',),
        ),
        migrations.CreateModel(
            name='PerformanceReviewProxy',
            fields=[
            ],
            options={
                'verbose_name': 'تقييم أداء',
                'verbose_name_plural': 'تقييمات الأداء',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.performancereview',),
        ),
        migrations.CreateModel(
            name='SystemMessageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'رسالة نظام',
                'verbose_name_plural': 'رسائل النظام',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.systemmessage',),
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
