# Generated by Django 5.2.12 on 2026-03-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayrollProxy',
        ),
    ]
