# Generated by Django 5.2.12 on 2026-04-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organization_sponsorship_employeefile_organization_and_more'),
        ('system', '0002_delete_payrollproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchProxy',
            fields=[
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.branch',),
        ),
        migrations.CreateModel(
            name='CostCenterProxy',
            fields=[
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.costcenter',),
        ),
        migrations.CreateModel(
            name='OrganizationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'مؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.organization',),
        ),
        migrations.CreateModel(
            name='SponsorshipProxy',
            fields=[
            ],
            options={
                'verbose_name': 'كفالة',
                'verbose_name_plural': 'الكفالات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.sponsorship',),
        ),
    ]
