# Generated by Django 5.2.12 on 2026-03-18 23:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم القسم')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رمز القسم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='مدير القسم')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='hr.departmentmodel', verbose_name='القسم الرئيسي')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('period_year', models.PositiveIntegerField(verbose_name='السنة')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بدل سكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بدل نقل')),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='بدلات أخرى')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ساعات إضافية')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ الساعات الإضافية')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الخصومات')),
                ('social_insurance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='التأمينات الاجتماعية')),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='خصم الغياب')),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='خصم السلف')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='صافي الراتب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'بانتظار الاعتماد'), ('approved', 'معتمد'), ('paid', 'مدفوع'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_employees', to='hr.departmentmodel', verbose_name='القسم')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.employeefile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'كشف راتب',
                'verbose_name_plural': 'كشوف الرواتب',
                'ordering': ['-period_year', '-period_month'],
                'indexes': [models.Index(fields=['period_year', 'period_month'], name='idx_payroll_period'), models.Index(fields=['status'], name='idx_payroll_status')],
                'unique_together': {('employee', 'period_month', 'period_year')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period_start', models.DateField(verbose_name='بداية فترة التقييم')),
                ('review_period_end', models.DateField(verbose_name='نهاية فترة التقييم')),
                ('work_quality', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='جودة العمل')),
                ('productivity', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الإنتاجية')),
                ('teamwork', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='العمل الجماعي')),
                ('punctuality', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الالتزام بالمواعيد')),
                ('initiative', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='المبادرة')),
                ('communication', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التواصل')),
                ('overall_rating', models.CharField(choices=[('excellent', 'ممتاز'), ('very_good', 'جيد جداً'), ('good', 'جيد'), ('acceptable', 'مقبول'), ('poor', 'ضعيف')], default='good', max_length=20, verbose_name='التقييم العام')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='الدرجة الإجمالية')),
                ('strengths', models.TextField(blank=True, null=True, verbose_name='نقاط القوة')),
                ('weaknesses', models.TextField(blank=True, null=True, verbose_name='نقاط الضعف')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='الأهداف المستقبلية')),
                ('reviewer_comments', models.TextField(blank=True, null=True, verbose_name='ملاحظات المُقيّم')),
                ('employee_comments', models.TextField(blank=True, null=True, verbose_name='تعليق الموظف')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='تم الاطلاع')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاطلاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hr.employeefile', verbose_name='الموظف')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='المُقيّم')),
            ],
            options={
                'verbose_name': 'تقييم أداء',
                'verbose_name_plural': 'تقييمات الأداء',
                'ordering': ['-review_period_end'],
                'indexes': [models.Index(fields=['overall_rating'], name='idx_perf_rating')],
            },
        ),
    ]
