# Generated by Django 5.2.12 on 2026-03-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departmentmodel_payroll_performancereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statementfile',
            options={'ordering': ['-created_at'], 'verbose_name': 'طلب إجازة', 'verbose_name_plural': 'طلبات الإجازة'},
        ),
    ]
