# Generated by Django 5.2.12 on 2026-03-24 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fix_attendancerecord_baserequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_assignments', to=settings.AUTH_USER_MODEL, verbose_name='معيّن إلى'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='branch_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_branch_approvals', to=settings.AUTH_USER_MODEL, verbose_name='معتمد من مدير الفرع'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='branch_manager_approval',
            field=models.CharField(choices=[('pending', 'معلّق'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='اعتماد مدير الفرع'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_completions', to=settings.AUTH_USER_MODEL, verbose_name='أنجز بواسطة'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='department_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_dept_approvals', to=settings.AUTH_USER_MODEL, verbose_name='معتمد من مدير الإدارة'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='department_manager_approval',
            field=models.CharField(choices=[('pending', 'معلّق'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='اعتماد مدير الإدارة'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='manager_approval',
            field=models.CharField(choices=[('pending', 'معلّق'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=20, verbose_name='اعتماد المدير العام'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_mgr_approvals', to=settings.AUTH_USER_MODEL, verbose_name='معتمد من المدير العام'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_uploads', to=settings.AUTH_USER_MODEL, verbose_name='رُفع بواسطة'),
        ),
    ]
