# Generated by Django 5.2.12 on 2026-03-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendancerecord_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل سكن'),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدلات أخرى'),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل نقل'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب الأساسي'),
        ),
    ]
