# Generated by Django 5.2.12 on 2026-03-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_branch_costcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancefile',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='employeefile',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_column='cost_center', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.costcenter', to_field='name', verbose_name='مركز التكلفة'),
        ),
        migrations.AlterField(
            model_name='employeetransferrequest',
            name='current_branch',
            field=models.ForeignKey(blank=True, db_column='current_branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.branch', to_field='name', verbose_name='الفرع الحالي'),
        ),
        migrations.AlterField(
            model_name='medicalexcuse',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_column='cost_center', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.costcenter', to_field='name', verbose_name='مركز التكلفة'),
        ),
        migrations.AlterField(
            model_name='medicalinsurance',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='salaryadjustment',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='salaryadjustment',
            name='cost_center',
            field=models.ForeignKey(blank=True, db_column='cost_center', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.costcenter', to_field='name', verbose_name='مركز التكلفة'),
        ),
        migrations.AlterField(
            model_name='statementfile',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='terminationfile',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='violationfile',
            name='branch',
            field=models.ForeignKey(blank=True, db_column='branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.branch', to_field='name', verbose_name='الفرع'),
        ),
        migrations.AlterField(
            model_name='violationfile',
            name='employee_branch',
            field=models.ForeignKey(blank=True, db_column='employee_branch', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.branch', to_field='name', verbose_name='فرع الموظف'),
        ),
    ]
