# Generated by Django 5.2.12 on 2026-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_employeetransferrequest_current_cost_center_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminationfile',
            name='last_working_date',
            field=models.DateField(blank=True, null=True, verbose_name='آخر تاريخ عمل'),
        ),
    ]
