# Generated by Django 5.2.12 on 2026-04-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_last_working_date_to_termination'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryadjustment',
            name='installments',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الأقساط'),
        ),
    ]
