# Generated by Django 5.2.12 on 2026-04-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_installments_to_salary_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancefile',
            name='installments',
            field=models.PositiveIntegerField(default=1, verbose_name='عدد الأقساط'),
        ),
    ]
