# Generated by Django 5.2.12 on 2026-04-03 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_installments_to_advance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم المؤسسة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='اسم الكفالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'كفالة',
                'verbose_name_plural': 'الكفالات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employeefile',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.organization', to_field='name', verbose_name='المؤسسة'),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='sponsorship',
            field=models.ForeignKey(blank=True, db_column='sponsorship', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.sponsorship', to_field='name', verbose_name='الكفالة'),
        ),
    ]
