# Generated by Django 5.2.12 on 2026-04-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_organization_sponsorship_employeefile_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='insurance_category',
            field=models.CharField(blank=True, choices=[('VVIP', 'VVIP'), ('A', 'A'), ('B3', 'B3'), ('MP2', 'MP2'), ('MP3', 'MP3'), ('MP4', 'MP4')], max_length=10, null=True, verbose_name='فئة التأمين'),
        ),
    ]
