# Generated by Django 5.2.12 on 2026-04-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_insurance_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='external_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل خارجي'),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='insurance_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة التأمين'),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='overtime_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل عمل إضافي'),
        ),
    ]
