# Generated by Django 5.2.12 on 2026-04-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_salary_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='is_on_leave',
            field=models.BooleanField(default=False, verbose_name='إجازة'),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='موقوف'),
        ),
    ]
