# Generated by Django 5.2.12 on 2026-04-03 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_worker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefile',
            name='leave_from',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ بداية الإجازة'),
        ),
        migrations.AddField(
            model_name='employeefile',
            name='suspended_from',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الإيقاف'),
        ),
        migrations.CreateModel(
            name='WorkerStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_type', models.CharField(choices=[('suspended', 'موقوف'), ('leave', 'إجازة')], max_length=20, verbose_name='نوع الحالة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.employeefile', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل حالة عامل',
                'verbose_name_plural': 'سجل حالات العمال',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
