# Generated by Django 5.2.12 on 2026-03-18 11:44

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceFileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'طلب سلفة',
                'verbose_name_plural': 'السلف',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.advancefile',),
        ),
        migrations.CreateModel(
            name='EmployeeFileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'إضافة موظف',
                'verbose_name_plural': 'إضافة الموظفين',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeefile',),
        ),
        migrations.CreateModel(
            name='SalaryAdjustmentProxy',
            fields=[
            ],
            options={
                'verbose_name': 'تعديل راتب',
                'verbose_name_plural': 'تعديلات الرواتب',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.salaryadjustment',),
        ),
        migrations.CreateModel(
            name='StatementFileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'إجازة',
                'verbose_name_plural': 'الإجازات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.statementfile',),
        ),
        migrations.CreateModel(
            name='TerminationFileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'إنهاء خدمة',
                'verbose_name_plural': 'إنهاء الخدمات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.terminationfile',),
        ),
    ]
