# Generated by Django 5.2.12 on 2026-03-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
        ('core', '0003_alter_statementfile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransferRequestProxy',
            fields=[
            ],
            options={
                'verbose_name': 'طلب نقل',
                'verbose_name_plural': 'طلبات النقل',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.employeetransferrequest',),
        ),
        migrations.CreateModel(
            name='MedicalExcuseProxy',
            fields=[
            ],
            options={
                'verbose_name': 'عذر طبي',
                'verbose_name_plural': 'الأعذار الطبية',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.medicalexcuse',),
        ),
        migrations.CreateModel(
            name='MedicalInsuranceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'تأمين طبي',
                'verbose_name_plural': 'التأمين الطبي',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.medicalinsurance',),
        ),
    ]
