# Generated by Django 5.2.12 on 2026-03-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_employeetransferrequestproxy_medicalexcuseproxy_and_more'),
        ('core', '0005_alter_attendancerecord_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecordProxy',
            fields=[
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.attendancerecord',),
        ),
        migrations.CreateModel(
            name='ViolationFileProxy',
            fields=[
            ],
            options={
                'verbose_name': 'مخالفة',
                'verbose_name_plural': 'المخالفات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hr.violationfile',),
        ),
    ]
