# Generated by Django 5.2.12 on 2026-03-24 00:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_attendancerecord_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollProxy',
            fields=[
            ],
            options={
                'verbose_name': 'كشف راتب',
                'verbose_name_plural': 'كشوف الرواتب',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.payroll',),
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2099)], verbose_name='السنة')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('generated', 'تم التوليد'), ('approved', 'معتمدة'), ('paid', 'تم الصرف'), ('closed', 'مغلقة')], db_index=True, default='open', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('generated_employees', models.PositiveIntegerField(default=0, verbose_name='عدد الموظفين المُولَّدة رواتبهم')),
                ('skipped_employees', models.PositiveIntegerField(default=0, verbose_name='موظفون تم تخطيهم (موجودون مسبقاً)')),
                ('total_basic', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الرواتب الأساسية')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الصافي')),
                ('generated_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوليد')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الصرف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='اعتمده')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payroll_periods', to=settings.AUTH_USER_MODEL, verbose_name='ولّده')),
            ],
            options={
                'verbose_name': 'فترة رواتب',
                'verbose_name_plural': 'فترات الرواتب',
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
