# Generated by Django 5.2.12 on 2026-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saudi_social_insurance_rate', models.DecimalField(decimal_places=4, default=0.09, help_text='مثال: 0.09 تعني 9%', max_digits=5, verbose_name='نسبة التأمينات (سعودي)')),
                ('non_saudi_social_insurance_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='مثال: 0.00 تعني 0%', max_digits=5, verbose_name='نسبة التأمينات (غير سعودي)')),
            ],
            options={
                'verbose_name': 'إعدادات المالية',
                'verbose_name_plural': 'إعدادات المالية',
            },
        ),
    ]
