# Generated by Django 5.2.12 on 2026-03-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_financesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollperiod',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='payroll_excel/%Y/', verbose_name='ملف الإكسيل المولد'),
        ),
    ]
